# Generated by Django 3.0.2 on 2020-03-27 21:30

import Apps.Usuarios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disquera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField()),
                ('fecha_nacimiento', models.DateField()),
                ('pais', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to=Apps.Usuarios.models.images_path)),
                ('is_artist', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='foto',
            field=models.ImageField(upload_to=Apps.Usuarios.models.images_path),
        ),
        migrations.CreateModel(
            name='UsuarioCanciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Cancion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario'),
        ),
    ]
